### ISSUE TITLE
Not working with Chrome Stable (Version 62.0.3202.62)

### ISSUE THREAD

**Issue by andrepcg** [joelgriffith/navalia#65]
After updating to Chrome Version 62.0.3202.62 tests started failing.

```
    unexpected server response (404)

      at ClientRequest._req.on (node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:651:26)
      at emitOne (events.js:115:13)
      at ClientRequest.emit (events.js:210:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:565:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
      at Socket.socketOnData (_http_client.js:454:20)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at addChunk (_stream_readable.js:266:12)
      at readableAddChunk (_stream_readable.js:253:11)
```

**Comment by andrepcg** [comment]
This is exactly the issue I ran into: https://github.com/cyrus-and/chrome-remote-interface/issues/288

**Comment by joelgriffith** [comment]
Ouch... I'm curious if you'd be interested in moving over to `puppeteer` since that project is well established and resourced. Is there something more elaborate that you need in Navalia since I'm in the process of deprecating it?

Thanks for reporting, btw!

**Comment by MilesOkeefe** [comment]
@joelgriffith deprecating what, Navalia? 

If so, can we get a warning at the top of the readme? I would have implemented puppeteer rather than navalia from the beginning if I knew that this had been sunsetted.

**Comment by joelgriffith** [comment]
@MilesOkeefe I was originally going to be sunsetting this project, but feel there's still room for it after some careful consideration.

I'll take a look at this issue in the coming days as I ramp back up on this.

Thanks folks!
